branches:
  only:
  - master2
  - stable
language: java
jdk:
- oraclejdk8
before_install:
install:
- mvn clean install -Dgpg.skip=true
before_script: 
script:
after_success:
- 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash after_success.sh; fi'



