branches:
  only:
  - master2
  - stable
language: java
jdk:
- oraclejdk8
before_install:
install:
- mvn clean install -Dgpg.skip=true
before_script: 
script: 
after_success:
- chmod a+x after_success.sh
- ./after_success.sh


